version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
  
  web:
    image: nginx
    ports: 
      - 80:80
    depends_on: 
      - app
    volumes: 
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432